# Generated by Django 4.2.7 on 2024-04-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
