# Generated by Django 4.2.7 on 2024-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_statistic', '0002_alter_userstatistics_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
