# Generated by Django 4.2.7 on 2024-05-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Страница', max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('page_link', models.CharField(max_length=255, unique=True)),
                ('qr_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('visits_phone', models.PositiveIntegerField(default=0)),
                ('visits_comp', models.PositiveIntegerField(default=0)),
                ('click_links', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_pages.page')),
            ],
        ),
    ]
