# Generated by Django 4.2.7 on 2024-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='qr_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='Страница', max_length=100),
        ),
    ]
