# Generated by Django 4.2.7 on 2024-05-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_pages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='qr_link',
        ),
    ]
