# Generated by Django 4.2.7 on 2024-04-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_pages', '0002_alter_page_page_link_alter_page_qr_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('visits_phone', models.PositiveIntegerField(default=0)),
                ('visits_comp', models.PositiveIntegerField(default=0)),
                ('click_links', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_pages.page')),
            ],
        ),
    ]
