# Generated by Django 4.2.7 on 2024-05-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_pages', '0004_page_qr_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='qr_link',
        ),
    ]
