# Generated by Django 4.2.7 on 2024-04-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_pages', '0004_alter_pagestatistics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='qr_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
